- hosts: all
  tasks:
  - name: Configuring yum repository for docker
    yum_repository:
     name: "docker"
     description: "Configure docker"
     baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
     gpgcheck: no

  - name: Installing Docker
    package:
     name: "docker-ce-18.06.3.ce-3.el7.x86_64"
     state: present
 
  - name: Starting Docker Services
    service:
     name: docker
     state: started
     enabled: yes

  - name: Install Docker SDK for python3
    command: "pip3 install docker-py"

  - name: Pull Docker httpd Image
    docker_image:
     name: httpd
     tag: latest
     source: pull

  - name: Copy webpage 
    copy:
     src: "my.html"
     dest: "/var/www/html/index.html"

  - name: Launching Docker Container
    docker_container:
     name: httpd
     image: httpd
     state: started
     exposed_ports: 
     - "80"
     ports: 
     - "8888:80"
     
